# Generated by Django 4.2.1 on 2023-07-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_banner_category_contact_customers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='image_url',
            field=models.CharField(max_length=2085),
        ),
    ]
