# Generated by Django 4.2.1 on 2023-07-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_banner_image_url_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AddField(
            model_name='product_images',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product_images',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
