# Generated by Django 4.2.1 on 2023-07-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_category_categories_rename_product_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(default='Product Description', max_length=2085),
            preserve_default=False,
        ),
    ]
