# Generated by Django 4.2.1 on 2023-07-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_contact_email_remove_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='product_images',
            name='image_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
